export const transactions = [
  {
    Date: '8/21/23',
    'Original Date': '8/21/23',
    Description: 'Venmo',
    'Original Description': 'VENMO - PAYMENT',
    Amount: -100.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/19/23',
    'Original Date': '8/19/23',
    Description: 'Burnt Hills Hardware',
    'Original Description': 'BURNT HILLS HARDWARE',
    Amount: -16.87,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/18/23',
    'Original Date': '8/18/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -10.0,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/18/23',
    'Original Date': '8/18/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -3.6,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/17/23',
    'Original Date': '8/17/23',
    Description:
      'Transfer From Matthew D Simoni Account # Xxxx0800 At Ext Bank Aba # 2213Xxxxx',
    'Original Description':
      'TRANSFER FROM MATTHEW D SIMONI ACCOUNT # XXXX0800 AT EXT BANK ABA # 2213XXXXX',
    Amount: 100.0,
    'Account Name': 'SAVINGS CONNECT',
  },
  {
    Date: '8/17/23',
    'Original Date': '8/17/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -25.21,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/17/23',
    'Original Date': '8/17/23',
    Description: 'Aldi',
    'Original Description': 'ALDI 65183               GLENVILLE    NY',
    Amount: -61.75,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/17/23',
    'Original Date': '8/17/23',
    Description: 'Amazon',
    'Original Description': 'AMZN Mktp US*TO8C64DG0   Amzn.com/billWA',
    Amount: -31.98,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/17/23',
    'Original Date': '8/17/23',
    Description: 'Etsy',
    'Original Description': 'Etsy.com - CherCanDoIt   718-8557955  NY',
    Amount: -29.38,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/17/23',
    'Original Date': '8/17/23',
    Description: 'Simoni Matthew D - Transfer',
    'Original Description': 'SIMONI MATTHEW D - TRANSFER',
    Amount: -100.0,
    'Account Name': 'Sunmark Savings',
  },
  {
    Date: '8/16/23',
    'Original Date': '8/16/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -6.1,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/16/23',
    'Original Date': '8/16/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -40.01,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/16/23',
    'Original Date': '8/16/23',
    Description: 'First Tech Fcu - Extrnltfr',
    'Original Description': 'First Tech FCU - ExtrnlTfr',
    Amount: -700.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/16/23',
    'Original Date': '8/16/23',
    Description: 'National Grid',
    'Original Description': 'NGRID36 - NGRID36WEB',
    Amount: -236.44,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/15/23',
    'Original Date': '8/15/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -22.89,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/15/23',
    'Original Date': '8/15/23',
    Description: '365 Market',
    'Original Description': '365 Market 888 432-32',
    Amount: -2.18,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/15/23',
    'Original Date': '8/15/23',
    Description: 'Chipotle',
    'Original Description': 'CHIPOTLE ONLINE          CHIPOTLE.COM CA',
    Amount: -30.4,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/15/23',
    'Original Date': '8/15/23',
    Description: 'Brightwheel - Brghtwhl*.',
    'Original Description': 'brightwheel - BRGHTWHL*.',
    Amount: -664.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/14/23',
    'Original Date': '8/14/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -15.0,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/14/23',
    'Original Date': '8/14/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -35.24,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/14/23',
    'Original Date': '8/14/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -37.63,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/14/23',
    'Original Date': '8/14/23',
    Description: 'Venmo',
    'Original Description': 'VENMO - PAYMENT',
    Amount: -35.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/12/23',
    'Original Date': '8/12/23',
    Description: 'Burnt Hills Hardware',
    'Original Description': 'BURNT HILLS HARDWARE',
    Amount: -12.4,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/11/23',
    'Original Date': '8/11/23',
    Description: 'Amazon',
    'Original Description': 'AMZN Mktp US*TO84E3342   Amzn.com/billWA',
    Amount: -36.67,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/11/23',
    'Original Date': '8/11/23',
    Description: 'New York Life Gr - Prearrange',
    'Original Description': 'NEW YORK LIFE GR - PREARRANGE',
    Amount: 1131.09,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/11/23',
    'Original Date': '8/11/23',
    Description: 'Glenville Beverage',
    'Original Description': 'GLENVILLE BEVERAGE',
    Amount: -26.51,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/10/23',
    'Original Date': '8/10/23',
    Description: 'Fid Bkg Svc Llc - Moneyline',
    'Original Description': 'FID BKG SVC LLC - MONEYLINE',
    Amount: -25.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/9/23',
    'Original Date': '8/9/23',
    Description: 'Target',
    'Original Description': 'TARGET',
    Amount: -59.98,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/9/23',
    'Original Date': '8/9/23',
    Description: 'Target',
    'Original Description': 'TARGET',
    Amount: 14.81,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/9/23',
    'Original Date': '8/9/23',
    Description: 'Aldi',
    'Original Description': 'ALDI 65183               GLENVILLE    NY',
    Amount: -63.33,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/9/23',
    'Original Date': '8/9/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -30.04,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/8/23',
    'Original Date': '8/8/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -54.62,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/8/23',
    'Original Date': '8/8/23',
    Description: 'Dollar Tree',
    'Original Description': 'DOLLAR TREE              GLENVILLE    NY',
    Amount: -12.15,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/8/23',
    'Original Date': '8/8/23',
    Description: 'Justblinds.Com #2152     Houston      Tx',
    'Original Description': 'JUSTBLINDS.COM #2152     HOUSTON      TX',
    Amount: -248.84,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/8/23',
    'Original Date': '8/8/23',
    Description: 'Fluor Marine Pro - Payroll',
    'Original Description': 'FLUOR MARINE PRO - PAYROLL',
    Amount: 932.9,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/8/23',
    'Original Date': '8/8/23',
    Description: 'Fluor Marine Pro - Payroll',
    'Original Description': 'FLUOR MARINE PRO - PAYROLL',
    Amount: 250.0,
    'Account Name': 'Sunmark Savings',
  },
  {
    Date: '8/8/23',
    'Original Date': '8/8/23',
    Description: 'Cit Bank Div Of - Transfer Simoni Matthew',
    'Original Description': 'CIT BANK DIV OF - TRANSFER SIMONI MATTHEW',
    Amount: 1964.8,
    'Account Name': 'Sunmark Savings',
  },
  {
    Date: '8/7/23',
    'Original Date': '8/7/23',
    Description:
      'Transfer To Matthew D Simoni Account # Xxxx0800 At Ext Bank Aba # 2213Xxxxx',
    'Original Description':
      'TRANSFER TO MATTHEW D SIMONI ACCOUNT # XXXX0800 AT EXT BANK ABA # 2213XXXXX',
    Amount: -1964.8,
    'Account Name': 'SAVINGS CONNECT',
  },
  {
    Date: '8/7/23',
    'Original Date': '8/7/23',
    Description: 'Carters, Inc.',
    'Original Description': 'carters, Inc.',
    Amount: -16.8,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/7/23',
    'Original Date': '8/7/23',
    Description: 'Bowman Orchards',
    'Original Description': 'BOWMAN ORCHARDS',
    Amount: -14.45,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/7/23',
    'Original Date': '8/7/23',
    Description: 'Bowman Orchards',
    'Original Description': 'WPY*Bowman Orchards LL',
    Amount: -8.24,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/7/23',
    'Original Date': '8/7/23',
    Description: 'Freemans Bridge Wine A',
    'Original Description': 'FREEMANS BRIDGE WINE A',
    Amount: -41.9,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/6/23',
    'Original Date': '8/6/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -188.02,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '8/5/23',
    'Original Date': '8/5/23',
    Description: 'Amazon',
    'Original Description': 'AMZN Mktp US*TA43Y9AG2   Amzn.com/billWA',
    Amount: -22.71,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/5/23',
    'Original Date': '8/5/23',
    Description: 'Nysdec Hunt/Fish License 866-933-2257 Ky',
    'Original Description': 'NYSDEC HUNT/FISH LICENSE 866-933-2257 KY',
    Amount: -32.0,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/5/23',
    'Original Date': '8/5/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -20.1,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/5/23',
    'Original Date': '8/5/23',
    Description: 'Mobile Latham Mdus Cu Services',
    'Original Description': 'Mobile Latham MDUS CU SERVICES',
    Amount: 156.99,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/4/23',
    'Original Date': '8/4/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -32.32,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/4/23',
    'Original Date': '8/4/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -18.99,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/4/23',
    'Original Date': '8/4/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -110.78,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '8/4/23',
    'Original Date': '8/4/23',
    Description: 'S&B 5 Mart-Citgo',
    'Original Description': 'S&B 5 MART-CITGO',
    Amount: -17.24,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/3/23',
    'Original Date': '8/3/23',
    Description: 'S&B 5 Mart-Citgo Schenectady Ny\nL18897010',
    'Original Description': 'S&B 5 MART-CITGO SCHENECTADY NY\nL18897010',
    Amount: -90.14,
    'Account Name': 'Discover',
  },
  {
    Date: '8/3/23',
    'Original Date': '8/3/23',
    Description: 'Stax *Wades Tree Se',
    'Original Description': 'STAX *WADES TREE SE',
    Amount: -1964.8,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/3/23',
    'Original Date': '8/3/23',
    Description: 'Chipotle',
    'Original Description': 'CHIPOTLE ONLINE          CHIPOTLE.COM CA',
    Amount: -5.4,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/2/23',
    'Original Date': '8/2/23',
    Description: 'Twin Bridges Was - Eft',
    'Original Description': 'TWIN BRIDGES WAS - EFT',
    Amount: -30.24,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'Burnt Hills Hardware',
    'Original Description': 'BURNT HILLS HARDWARE',
    Amount: 9.73,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'Dunkin Donuts',
    'Original Description': "DUNKIN' MOBILE",
    Amount: -15.0,
    'Account Name': 'Captial One',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'Spotify Usa              877-7781161  Ny',
    'Original Description': 'Spotify USA              877-7781161  NY',
    Amount: -10.99,
    'Account Name': 'Bank of America',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -2.58,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -14.81,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'Brightwheel - Brghtwhl*.',
    'Original Description': 'brightwheel - BRGHTWHL*.',
    Amount: -664.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'New York Life Gr - Prearrange',
    'Original Description': 'NEW YORK LIFE GR - PREARRANGE',
    Amount: 1131.09,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '8/1/23',
    'Original Date': '8/1/23',
    Description: 'New York Life Gr - Prearrange',
    'Original Description': 'NEW YORK LIFE GR - PREARRANGE',
    Amount: 1131.09,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Interest Credit',
    'Original Description': 'INTEREST CREDIT',
    Amount: 46.78,
    'Account Name': 'SAVINGS CONNECT',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Spectrum 855-707-7328 Mo\nRc282177092',
    'Original Description': 'SPECTRUM 855-707-7328 MO\nRC282177092',
    Amount: -79.99,
    'Account Name': 'Discover',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Target',
    'Original Description': 'TARGET',
    Amount: -7.71,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -15.0,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -57.53,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -101.12,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Capital One CC Payment',
    'Original Description': 'CAPITAL ONE - MOBILE PMT',
    Amount: -660.11,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Lowes Cc - Lws Epay',
    'Original Description': 'Lowes CC - LWS EPAY',
    Amount: -216.2,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Bank of America CC Payment',
    'Original Description': 'BK OF AMER VISA - ONLINE PMT',
    Amount: -1149.2,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Venmo - Cashout',
    'Original Description': 'VENMO - CASHOUT',
    Amount: 7.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Verizon Wireless - Payments',
    'Original Description': 'VERIZON WIRELESS - PAYMENTS',
    Amount: -133.02,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Discover - E-Payment',
    'Original Description': 'DISCOVER - E-PAYMENT',
    Amount: -213.42,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Target Card Srvc - Bill Pay',
    'Original Description': 'TARGET CARD SRVC - BILL PAY',
    Amount: -392.35,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Dividend',
    'Original Description': 'Dividend',
    Amount: 0.02,
    'Account Name': 'Sunmark Savings',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Dividend',
    'Original Description': 'Dividend',
    Amount: 0.25,
    'Account Name': 'YOUTH SAVINGS',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'S&B 5 Mart-Citgo',
    'Original Description': 'S&B 5 MART-CITGO',
    Amount: -17.24,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Burnt Hills Hardware',
    'Original Description': 'BURNT HILLS HARDWARE',
    Amount: -10.69,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/31/23',
    'Original Date': '7/31/23',
    Description: 'Burnt Hills Hardware',
    'Original Description': 'BURNT HILLS HARDWARE',
    Amount: -13.39,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/29/23',
    'Original Date': '7/29/23',
    Description: 'No Details Available',
    'Original Description': 'No Details Available',
    Amount: 216.2,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/29/23',
    'Original Date': '7/29/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -7.48,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/29/23',
    'Original Date': '7/29/23',
    Description: 'Ba Electronic Payment',
    'Original Description': 'BA ELECTRONIC PAYMENT',
    Amount: 1149.2,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/29/23',
    'Original Date': '7/29/23',
    Description: 'Target CC Payment',
    'Original Description': 'E-PAYMENT, TARGET.COM',
    Amount: 392.35,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Internet Payment - Thank You',
    'Original Description': 'INTERNET PAYMENT - THANK YOU',
    Amount: 213.42,
    'Account Name': 'Discover',
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: 306.77,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -30.27,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -306.77,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Capital One CC Payment',
    'Original Description': 'CAPITAL ONE MOBILE PYMT AuthDate 28-Jul',
    Amount: 660.11,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Mobile Latham Mdus Cu Services',
    'Original Description': 'Mobile Latham MDUS CU SERVICES',
    Amount: 61.2,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Erie Canalway He - Payroll',
    'Original Description': 'ERIE CANALWAY HE - PAYROLL',
    Amount: 744.4,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/28/23',
    'Original Date': '7/28/23',
    Description: 'Travelers - Per Insur',
    'Original Description': 'TRAVELERS - PER INSUR',
    Amount: -96.89,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/27/23',
    'Original Date': '7/27/23',
    Description: "Stewart's",
    'Original Description': 'STEWARTS SHOP 109',
    Amount: -11.32,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/27/23',
    'Original Date': '7/27/23',
    Description: 'Fid Bkg Svc Llc - Moneyline',
    'Original Description': 'FID BKG SVC LLC - MONEYLINE',
    Amount: -25.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/26/23',
    'Original Date': '7/26/23',
    Description: '365 Market',
    'Original Description': '365 MARKET FP',
    Amount: -9.86,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/26/23',
    'Original Date': '7/26/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -39.19,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/26/23',
    'Original Date': '7/26/23',
    Description: 'Roundpoint Mtg - Payments',
    'Original Description': 'ROUNDPOINT MTG - PAYMENTS',
    Amount: -1767.6,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/25/23',
    'Original Date': '7/25/23',
    Description: 'Fluor Marine Pro - Payroll',
    'Original Description': 'FLUOR MARINE PRO - PAYROLL',
    Amount: 2466.55,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/25/23',
    'Original Date': '7/25/23',
    Description: 'Fluor Marine Pro - Payroll',
    'Original Description': 'FLUOR MARINE PRO - PAYROLL',
    Amount: 250.0,
    'Account Name': 'Sunmark Savings',
  },
  {
    Date: '7/24/23',
    'Original Date': '7/24/23',
    Description: 'Apple.Com/Bill',
    'Original Description': 'APPLE.COM/BILL',
    Amount: -17.27,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/24/23',
    'Original Date': '7/24/23',
    Description: 'S&B 5 Mart-Citgo',
    'Original Description': 'S&B 5 MART-CITGO',
    Amount: -12.93,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/24/23',
    'Original Date': '7/24/23',
    Description: 'Personal Wine Cellar',
    'Original Description': 'Personal Wine Cellar',
    Amount: -9.71,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/24/23',
    'Original Date': '7/24/23',
    Description: 'Amazon',
    'Original Description': 'AMZN Mktp US*0J3IL32G3   Amzn.com/billWA',
    Amount: -38.07,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/24/23',
    'Original Date': '7/24/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -162.69,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/24/23',
    'Original Date': '7/24/23',
    Description: 'Target',
    'Original Description': 'TARGET',
    Amount: -46.85,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/22/23',
    'Original Date': '7/22/23',
    Description: 'Sq *West End Bagels',
    'Original Description': 'SQ *WEST END BAGELS',
    Amount: -22.2,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/22/23',
    'Original Date': '7/22/23',
    Description: 'Mealeo Jade Bistro       Mealeo.Com   Ny',
    'Original Description': 'MEALEO JADE BISTRO       MEALEO.COM   NY',
    Amount: -67.85,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/21/23',
    'Original Date': '7/21/23',
    Description: 'Netflix.Com Netflix.Com Ca\nNetflix.Com',
    'Original Description': 'NETFLIX.COM NETFLIX.COM CA\nNETFLIX.COM',
    Amount: -16.73,
    'Account Name': 'Discover',
  },
  {
    Date: '7/21/23',
    'Original Date': '7/21/23',
    Description: 'Amazon',
    'Original Description': 'Amazon.com*N36I35U13     Amzn.com/billWA',
    Amount: -15.81,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/21/23',
    'Original Date': '7/21/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -11.58,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/20/23',
    'Original Date': '7/20/23',
    Description: 'Apple.Com/Bill',
    'Original Description': 'APPLE.COM/BILL',
    Amount: -2.99,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/20/23',
    'Original Date': '7/20/23',
    Description: "Stewart's",
    'Original Description': 'STEWARTS SHOP 468',
    Amount: -32.47,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/20/23',
    'Original Date': '7/20/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -10.87,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/20/23',
    'Original Date': '7/20/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -63.84,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/19/23',
    'Original Date': '7/19/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -83.55,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/19/23',
    'Original Date': '7/19/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -92.21,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/19/23',
    'Original Date': '7/19/23',
    Description: 'Scotts Lawn Program      877-2203091  Oh',
    'Original Description': 'SCOTTS LAWN PROGRAM      877-2203091  OH',
    Amount: -139.53,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/19/23',
    'Original Date': '7/19/23',
    Description: 'National Grid',
    'Original Description': 'NGRID36 - NGRID36WEB',
    Amount: -202.91,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/18/23',
    'Original Date': '7/18/23',
    Description: "Stewart's",
    'Original Description': 'STEWARTS SHOP 183',
    Amount: -52.84,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/18/23',
    'Original Date': '7/18/23',
    Description: "Stewart's",
    'Original Description': 'STEWARTS SHOP 183',
    Amount: -13.69,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/18/23',
    'Original Date': '7/18/23',
    Description:
      'Transfer From Matthew D Simoni Account # Xxxx0800 At Ext Bank Aba # 2213Xxxxx',
    'Original Description':
      'TRANSFER FROM MATTHEW D SIMONI ACCOUNT # XXXX0800 AT EXT BANK ABA # 2213XXXXX',
    Amount: 100.0,
    'Account Name': 'SAVINGS CONNECT',
  },
  {
    Date: '7/18/23',
    'Original Date': '7/18/23',
    Description: 'Lowes Internet Fufillmnt',
    'Original Description': 'LOWES INTERNET FUFILLMNT',
    Amount: -13.09,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/18/23',
    'Original Date': '7/18/23',
    Description: 'Brightwheel - Brghtwhl*.',
    'Original Description': 'brightwheel - BRGHTWHL*.',
    Amount: -664.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/18/23',
    'Original Date': '7/18/23',
    Description: 'First Tech Fcu - Extrnltfr',
    'Original Description': 'First Tech FCU - ExtrnlTfr',
    Amount: -700.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/18/23',
    'Original Date': '7/18/23',
    Description: 'Simoni Matthew D - Transfer',
    'Original Description': 'SIMONI MATTHEW D - TRANSFER',
    Amount: -100.0,
    'Account Name': 'Sunmark Savings',
  },
  {
    Date: '7/16/23',
    'Original Date': '7/16/23',
    Description: "Par*Dibella'S Subs - 121 Latham Ny",
    'Original Description': "PAR*DIBELLA'S SUBS - 121 LATHAM NY",
    Amount: -29.12,
    'Account Name': 'Discover',
  },
  {
    Date: '7/16/23',
    'Original Date': '7/16/23',
    Description: "Mcdonald'S F6032 Schenectady Ny",
    'Original Description': "MCDONALD'S F6032 SCHENECTADY NY",
    Amount: -8.09,
    'Account Name': 'Discover',
  },
  {
    Date: '7/15/23',
    'Original Date': '7/15/23',
    Description: "Wendy's",
    'Original Description': "WENDY'S LATHAM LATHAM NY",
    Amount: -22.12,
    'Account Name': 'Discover',
  },
  {
    Date: '7/15/23',
    'Original Date': '7/15/23',
    Description: 'Duck Donuts Latham Latham Ny',
    'Original Description': 'DUCK DONUTS LATHAM LATHAM NY',
    Amount: -15.65,
    'Account Name': 'Discover',
  },
  {
    Date: '7/14/23',
    'Original Date': '7/14/23',
    Description: 'Stadium Golf Club - Pr',
    'Original Description': 'STADIUM GOLF CLUB - PR',
    Amount: -32.96,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/14/23',
    'Original Date': '7/14/23',
    Description: "Stewart's",
    'Original Description': 'STEWARTS SHOP 126',
    Amount: -15.09,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/14/23',
    'Original Date': '7/14/23',
    Description: 'S&B 5 Mart-Citgo',
    'Original Description': 'S&B 5 MART-CITGO',
    Amount: -8.62,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/14/23',
    'Original Date': '7/14/23',
    Description: 'Lakeside Farms Ballston Lakeny',
    'Original Description': 'LAKESIDE FARMS BALLSTON LAKENY',
    Amount: -37.17,
    'Account Name': 'Discover',
  },
  {
    Date: '7/14/23',
    'Original Date': '7/14/23',
    Description: "Wendy's",
    'Original Description': "WENDY'S GLENVILLE GLENVILLE NY",
    Amount: -14.66,
    'Account Name': 'Discover',
  },
  {
    Date: '7/14/23',
    'Original Date': '7/14/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -97.31,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/14/23',
    'Original Date': '7/14/23',
    Description: 'Mighty Kicks             Httpswww.Capiny',
    'Original Description': 'MIGHTY KICKS             HTTPSWWW.CAPINY',
    Amount: -117.0,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/13/23',
    'Original Date': '7/13/23',
    Description: '365 Market',
    'Original Description': '365 MARKET 888 432-3299 TROY MI',
    Amount: -4.73,
    'Account Name': 'Discover',
  },
  {
    Date: '7/13/23',
    'Original Date': '7/13/23',
    Description: 'Amazon',
    'Original Description': 'AMZN Mktp US*AV0NK0HG3   Amzn.com/billWA',
    Amount: -73.89,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/13/23',
    'Original Date': '7/13/23',
    Description: 'Fid Bkg Svc Llc - Moneyline',
    'Original Description': 'FID BKG SVC LLC - MONEYLINE',
    Amount: -25.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/13/23',
    'Original Date': '7/13/23',
    Description: 'Erie Canalway He - Payroll',
    'Original Description': 'ERIE CANALWAY HE - PAYROLL',
    Amount: 1997.45,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/12/23',
    'Original Date': '7/12/23',
    Description: 'Dunkin Donuts',
    'Original Description': "DUNKIN' MOBILE",
    Amount: -10.0,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/12/23',
    'Original Date': '7/12/23',
    Description: '365 Market',
    'Original Description': '365 MARKET 888 432-3299 TROY MI',
    Amount: -4.73,
    'Account Name': 'Discover',
  },
  {
    Date: '7/12/23',
    'Original Date': '7/12/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -62.73,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/11/23',
    'Original Date': '7/11/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -32.31,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/11/23',
    'Original Date': '7/11/23',
    Description: 'Amazon',
    'Original Description': 'Amazon.com*P17FK8823     Amzn.com/billWA',
    Amount: -9.66,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/11/23',
    'Original Date': '7/11/23',
    Description: 'Fluor Marine Pro - Payroll',
    'Original Description': 'FLUOR MARINE PRO - PAYROLL',
    Amount: 2466.54,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/11/23',
    'Original Date': '7/11/23',
    Description: 'Fluor Marine Pro - Payroll',
    'Original Description': 'FLUOR MARINE PRO - PAYROLL',
    Amount: 250.0,
    'Account Name': 'Sunmark Savings',
  },
  {
    Date: '7/10/23',
    'Original Date': '7/10/23',
    Description: 'Mealeo Jade Bistro',
    'Original Description': 'MEALEO JADE BISTRO',
    Amount: -54.36,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/10/23',
    'Original Date': '7/10/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -137.64,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/10/23',
    'Original Date': '7/10/23',
    Description: 'Target',
    'Original Description': 'TARGET',
    Amount: -18.37,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/10/23',
    'Original Date': '7/10/23',
    Description: 'Venmo',
    'Original Description': 'VENMO - PAYMENT',
    Amount: -100.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/10/23',
    'Original Date': '7/10/23',
    Description: 'Venmo',
    'Original Description': 'VENMO - PAYMENT',
    Amount: -19.0,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/9/23',
    'Original Date': '7/9/23',
    Description: 'Disney Plus 8889057888 Ca',
    'Original Description': 'DISNEY PLUS 8889057888 CA',
    Amount: -10.99,
    'Account Name': 'Discover',
  },
  {
    Date: '7/8/23',
    'Original Date': '7/8/23',
    Description: 'Personal Wine Cellar',
    'Original Description': 'Personal Wine Cellar',
    Amount: -58.31,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/8/23',
    'Original Date': '7/8/23',
    Description: 'Mdc*Realsimplemag Ms',
    'Original Description': 'MDC*RealSimpleMag MS',
    Amount: -23.0,
    'Account Name': 'Captial One',
  },
  {
    Date: '7/8/23',
    'Original Date': '7/8/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -10.26,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/8/23',
    'Original Date': '7/8/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -83.73,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/8/23',
    'Original Date': '7/8/23',
    Description: 'Target.Com',
    'Original Description': 'TARGET.COM',
    Amount: -22.57,
    'Account Name': 'Target Credit Card',
  },
  {
    Date: '7/8/23',
    'Original Date': '7/8/23',
    Description: 'Usps Po 3575340325       Schenectady  Ny',
    'Original Description': 'USPS PO 3575340325       SCHENECTADY  NY',
    Amount: -61.2,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/8/23',
    'Original Date': '7/8/23',
    Description: 'Hannaford',
    'Original Description': 'HANNAFORD #8376          GLENVILLE    NY',
    Amount: -27.38,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/7/23',
    'Original Date': '7/7/23',
    Description: "Wendy's",
    'Original Description': "WENDY'S GLENVILLE GLENVILLE NY",
    Amount: -19.08,
    'Account Name': 'Discover',
  },
  {
    Date: '7/7/23',
    'Original Date': '7/7/23',
    Description: 'Store 2701 Glenville Ny',
    'Original Description': 'STORE 2701 GLENVILLE NY',
    Amount: -48.17,
    'Account Name': "Lowe's Credit Card",
  },
  {
    Date: '7/6/23',
    'Original Date': '7/6/23',
    Description: 'Nysdec Hunt/Fish License 866-933-2257 Ky',
    'Original Description': 'NYSDEC HUNT/FISH LICENSE 866-933-2257 KY',
    Amount: -25.0,
    'Account Name': 'Bank of America',
  },
  {
    Date: '7/6/23',
    'Original Date': '7/6/23',
    Description: 'Discover - E-Payment',
    'Original Description': 'DISCOVER - E-PAYMENT',
    Amount: -508.96,
    'Account Name': 'Sunmark Checking',
  },
  {
    Date: '7/5/23',
    'Original Date': '7/5/23',
    Description: "Stewart's",
    'Original Description': 'STEWARTS SHOP 468',
    Amount: -11.32,
    'Account Name': 'Captial One',
  },
]
